---
- hosts: bpbl
  become: yes
  tasks:
   - name: Install git package
     package:
      name: git
      state: present
     tags:
      - update

   - name: Create backup path
     file:
      state: directory
      path: "{{BackupPath}}"
     tags:
      - backup

     
   - name: Backup htdocs folder
     archive:
      path: "{{HtdocsPath}}"
      dest: "{{BackupPath}}/htdocs.tar.bz2"
      format: bz2
     tags:
      - backup

   - name: Install python-pymysql package
     package:
      name:
       - python2-PyMySQL
       - python3-PyMySQL
       - python3-libselinux
      state: present
     tags:
      - backup
   
   - name: Backup databse
     mysql_db:
      name: "{{DbName}}"
      state: dump
      target: "{{BackupPath}}/{{DbName}}.bz2"
     tags:
      - backup

   - name: Update git repository
     git:
      repo: "{{CampaignRepoSsh}}"
      dest: "{{CampaignPath}}"
      clone: no
      accept_hostkey: yes
      force: yes
      version: "{{BranchName}}"
     notify:
      - Restart web daemon
     tags:
      - update

   - name: Apply selinux file context
     sefcontext:
      target: "{{CampaignPath}}"

  handlers:
   - name: Restart web daemon
     service:
      name: httpd
      state: restarted
...
