---
- hosts: bpbl
  become: yes
  tasks:
   - name: Install git package
     package:
      name: git
      state: present
     tags:
      - update

   - name: Create backup path
     file:
      state: directory
      path: "{{BackupPath}}"
     tags:
      - backup

     
   - name: Backup htdocs folder
     archive:
      path: "{{HtdocsPath}}"
      dest: "{{BackupPath}}/htdocs.tar.bz2"
      format: bz2
     tags:
      - backup

   - name: Install python-pymysql package
     package:
      name:
       - python3-libselinux
      state: present
     tags:
      - backup

   - name: Update git repository
     git:
      repo: "{{CampaignRepoSsh}}"
      dest: "./"
      accept_hostkey: yes
      force: yes
      version: "{{BranchName}}"
     notify:
      - Restart web daemon
     tags:
      - update

   - name: Copy files
     file:
      src: "./berger"
      path: "{{ CampaignPath }}/{{ CampaignName }}"
      setype: httpd_sys_content_t
      state: directory
     tags:
      - update


  handlers:
   - name: Restart web daemon
     service:
      name: httpd
      state: restarted
...
