---
- hosts: bpbl
  become: yes
  tasks:
   - name: Install git package
     package:
      name: git
      state: present
     tags:
      - update

   - name: Install python-pymysql package
     package:
      name:
       - python3-libselinux
      state: present
     tags:
      - backup

   - name: Update git repository
     git:
      repo: "{{ CampaignRepoSsh }}"
      dest: "{{ TargetCompaignName }}"
      accept_hostkey: yes
      force: yes
      version: "{{BranchName}}"
      recurse: yes
     notify:
      - Restart web daemon
     tags:
      - update

   - name: Copy files
     copy:
      src: "{{ TargetCompaignName }}"
      dest: "{{ CampaignPath }}"
      setype: httpd_sys_content_t
      remote_src: yes
     tags:
      - update


  handlers:
   - name: Restart web daemon
     service:
      name: httpd
      state: restarted
...
