---
- hosts: bpbl
  become: yes
  tasks:
   - name: Install git package
     package:
      name: git
      state: present
     tags:
      - update

   - name: Create backup path
     file:
      state: directory
      path: "{{BackupPath}}"
     tags:
      - backup

     
   - name: Backup htdocs folder
     archive:
      path: "{{HtdocsPath}}"
      dest: "{{BackupPath}}/prod.tar.bz2"
      format: bz2
     tags:
      - backup

   - name: Install python-pymysql package
     package:
      name:
       - python2-PyMySQL
       - python3-PyMySQL
      state: present
     tags:
      - backup
   
   - name: Backup databse
     mysql_db:
      name: "{{DbName}}"
      state: dump
      target: "{{BackupPath}}/{{DbName}}.bz2"
     tags:
      - backup

   - name: Update git repository
     git:
      repo: "{{RepoSsh}}"
      dest: "{{HtdocsPath}}"
      clone: no
      accept_hostkey: yes
      force: yes
      version: "{{BranchName}}"
     tags:
      - update
...
